general.import = [
       # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
       "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding.x = 5
padding.y = 5
opacity = 0.8
blur = true

[font]
size = 19.0
normal.family = "MesloLGS Nerd Font Mono"
# normal.style = "Italic"

